#!/bin/bash
stty echo
start=1
antal=8

#FTP CONNECTION
HOST='172.27.99.110'
USER='MC'
PASSWORD='P@ssw0rd'

#MYSQL INFORMATION
user="root"
password="P@ssw0rd"
host="localhost"
db_name="pex"

#BACKUP THE SERVERFILED
cd /home
	clear
	
	echo "STARTING BACKUP NOW"
	
lftp -u "$USER","$PASSWORD" $HOST <<EOF
	cd server
	rm -rf MC1
	rm -rf MC2
	rm -rf MC3
	rm -rf MC4
	rm -rf MC5
	rm -rf MC6
	rm -rf MC7
	rm -rf MC8
	rm -rf BC
	rm -rf mysql
EOF
	
	echo -e "{\e[32mSUCESS\e[39m} OLD BACKUP IS NOW REMOVED"
	
lftp -u "$USER","$PASSWORD" $HOST <<EOF
	cd server
	mkdir MC1
	mkdir MC1/serverfiles
	mkdir MC2
	mkdir MC2/serverfiles
	mkdir MC3
	mkdir MC3/serverfiles
	mkdir MC4
	mkdir MC4/serverfiles
	mkdir MC5
	mkdir MC5/serverfiles
	mkdir MC6
	mkdir MC6/serverfiles
	mkdir MC7
	mkdir MC7/serverfiles
	mkdir MC8
	mkdir MC8/serverfiles
	mkdir BC
	mkdir mysql
EOF

	echo -e "{\e[32mSUCESS\e[39m} CREATED THE NEW FOLDERS"

lftp -u "$USER","$PASSWORD" $HOST <<EOF
	mirror -R /home/MC1/serverfiles /server/MC1/serverfiles
	mirror -R /home/MC2/serverfiles /server/MC2/serverfiles
	mirror -R /home/MC3/serverfiles /server/MC3/serverfiles
	mirror -R /home/MC4/serverfiles /server/MC4/serverfiles
	mirror -R /home/MC5/serverfiles /server/MC5/serverfiles
	mirror -R /home/MC6/serverfiles /server/MC6/serverfiles
	mirror -R /home/MC7/serverfiles /server/MC7/serverfiles
	mirror -R /home/MC8/serverfiles /server/MC8/serverfiles
	mirror -R /home/BC /server/BC
	mirror -R /mysql /server/mysql
	exit
EOF

	echo -e "{\e[32mSUCESS\e[39m} UPLOAD IS FINISHED"
	
	rm -rf /mysql
	mkdir /mysql
	backup_path="/mysql"
	mysqldump --user=$user --password=$password --host=$host $db_name > $backup_path/$db_name.sql 2> /dev/null
	
	lftp -u "$USER","$PASSWORD" $HOST <<EOF
	mirror -R /mysql mysql
	exit
EOF

	echo -e "{\e[32mSUCESS\e[39m} MYSQL BACKUP"
	
	echo -e "{\e[32mSUCESS\e[39m} FINISHED BACKUP AND IT IS UPLOADED TO FTP"
	echo -e "FTP IP:\e[91m$HOST\e[39m";
	
	stty -echo
	date=$(date +"%d-%b-%Y")
	seconds=3600
	date1=$((`date +%s` + $seconds))
	
	while [ "$date1" -ge `date +%s` ]; do 
		echo -ne "BACKUP WILL RUN IN:  $(date -u --date @$(($date1 - `date +%s` )) +%H:%M:%S)\r"; 
	done
	
	cd
	./backup
	